# Generated by Django 5.1.7 on 2025-03-31 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0002_bloodcamp_remove_user_is_admin_remove_user_is_donor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
