# Generated by Django 5.1.7 on 2025-04-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0003_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodcamp',
            name='location',
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='applied_for_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='total_donations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='disease_history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
